import pandas as pd
df=pd.read_csv('weather.csv')
print(df)
print("--------------------------------1")
print(df['Temperature'].max())
print("--------------------------------2")
print(df['Temperature'].min())
print("--------------------------------3")
print(df[df.Temperature==df.Temperature.max()])
print("--------------------------------4")
print(df[df.Temperature==df.Temperature.min()])
print("--------------------------------5")
print(df[df.Events==df.Events])
print("--------------------------------6")
print(df.Events[df.Events==df.Events])
print("--------------------------------7")