import numpy as np
a=np.zeros((2,3,3))
print(a)
print(a.ndim)
b=np.ones((4,2))
print(b)
c=np.full((2,2),100)
print(c)
d=np.full_like(a,50)
print(d)
e=np.random.rand(4,2)
print(e)
f=np.random.randint(-4,8,size=(3,3))
print(f)
g=np.identity(5)
print(g)
print(b.T)